spring.application.name=kafka-consumer
server.port=8082

# ========================================================================
#          CONSUMER CONFIGURATION (order, payments topic)
# ========================================================================
# All of below properties is used to create KafkaConsumer object, it needs props
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=order-consumer-group

#spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

#spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.value.default.type=com.bsharan.kafka_consumer.models.Order


# ========================================================================
#          PRODUCER CONFIGURATION (for producing into payment topic)
# ========================================================================
# Kafka brokers where the producer connects
spring.kafka.producer.bootstrap-servers=localhost:9092,localhost:9192
# Serializes the Kafka message key from String to bytes
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Serializes PaymentStatus object into JSON bytes
spring.kafka.producer.value-serializer=com.bsharan.kafka_consumer.serializers.PaymentStatusSerializer
# Wait for acknowledgement from all required in-sync replicas
spring.kafka.producer.acks=all

# Kafka Consumer logs
#logging.level.org.apache.kafka.clients.consumer=DEBUG
#logging.level.org.apache.kafka.clients.consumer.internals=DEBUG

# Suppress Kafka configuration dump
logging.level.org.apache.kafka.common.config.AbstractConfig=WARN